ARG BASE_IMAGE="ghcr.io/gbraad-devenv/fedora/base"
ARG BASE_VERSION="42"

FROM ${BASE_IMAGE}:${BASE_VERSION}

LABEL org.opencontainers.image.source = "https://github.com/gbraad-devenv/fedora"

# audio support
RUN dnf install -y \
	pulseaudio \
	alsa-plugins-pulseaudio \
    && dnf clean all \
    && rm -rf /var/cache/yum

# graphical
RUN dnf install -y \
        novnc \
        x11vnc \
        i3 \
        python3-i3ipc \
        feh \
    && dnf clean all \
    && rm -rf /var/cache/yum

# fonts
RUN dnf install -y \
        adobe-source-han-mono-fonts \
        adobe-source-code-pro-fonts \
        adobe-source-sans-pro-fonts \
        adobe-source-serif-pro-fonts \
        powerline-fonts \
    && dnf clean all \
    && rm -rf /var/cache/yum

# kasmvnc
RUN dnf install -y https://github.com/spotsnel/AltRPMS-KasmVNC/releases/download/1.3.3/kasmvncserver-1.3.3-1.fc41.x86_64.rpm \
    && dnf clean all \
    && rm -rf /var/cache/yum \
    && usermod -a -G kasmvnc-cert gbraad

COPY ../../assets/kasmvncserver.service /etc/systemd/system
COPY ../../assets/kasmvnc.yaml /etc/kasmvnc/

COPY ../../assets/pulseaudio.service /etc/systemd/system

RUN usermod -aG pulse-access gbraad \
    && mkdir -p /etc/rdesktop

COPY ../../assets/rdesktop.ini /etc/rdesktop/rdesktop.ini
COPY ../../assets/rdesktopexec /usr/bin

RUN chown :users /etc/rdesktop/rdesktop.ini \
    && chmod g+w /etc/rdesktop/rdesktop.ini \
    && chown :users /etc/rdesktop \
    && chmod g+w /etc/rdesktop

RUN dnf install -y \
	nodejs \
    && dnf clean all \
    && rm -rf /var/cache/yum

# use release build of kclient
COPY curl -L https://github.com/gbraad-devenv/kclient/releases/download/0.2/kclient.zip -o /tmp/kclient.zip \
    && unzip /tmp/kclient.zip -d /opt/ \
    && rm /tmp/kclient.zip
COPY ../../assets/kclient.service /etc/systemd/system

# Userspace does not expose 100.100.100.100
#RUN sed -i 's/^FLAGS=".*"/FLAGS="--tun=userspace-networking"/' /etc/default/tailscaled

COPY ../../assets/generate-certs.service /etc/systemd/system
COPY ../../assets/generate-certs.sh /etc/rdesktop

USER gbraad

RUN mkdir -p ~/.vnc \
    && echo $'#!/bin/sh\ni3 &' > ~/.vnc/xstartup \
    && chmod +x ~/.vnc/xstartup \
    && /bin/bash -c "echo -e 'password\npassword\n\n' | kasmvncpasswd -u gbraad -w" \
    && touch ~/.vnc/.de-was-selected

# systemd is already set up in systemd image; make sure to use root
USER root

RUN systemctl enable kasmvncserver \
    && systemctl enable pulseaudio \
    && systemctl enable kclient \
    && systemctl enable generate-certs \
    && git config -f /etc/rdesktop/rdesktop.ini rdesktop.title "devenv rdesktop" \
    && git config -f /etc/rdesktop/rdesktop.ini rdesktop.exec "i3-sensible-terminal"

#ENTRYPOINT ["/sbin/init"]
