image: ghcr.io/gbraad/gitpod-devenv:v0.2.2

experimentalNetwork: true

tasks:
  - init: >
      ./gitpod/install.sh
  - name: tailscaled
    command: |
      sudo tailscaled
  - name: tailscale
    command: |
      sudo -E tailscale up --hostname "gitpod-${GITPOD_WORKSPACE_ID}" \
                           --authkey "${TAILSCALE_AUTHKEY}"
  - name: github
    command: |
      gh auth login -h github.com -w

ports:
  - port: 22
    onOpen: ignore
  - port: 6080
    onOpen: open-preview

vscode:
  extensions:
    - ms-vscode.Theme-TomorrowKit

