# v0.1.0 sha256:adb76dcf2cccd58f3e65e39f81df4cf64381c71c6b266bf0ec112ca64814244d
image: ghcr.io/gbraad/gitpod-devenv:latest

experimentalNetwork: true

tasks:
  - init: >
      ./gitpod/install.sh
  - name: tailscaled
    command: |
      sudo tailscaled
  - name: tailscale
    command: |
      sudo -E tailscale up --hostname "gitpod-${GITPOD_WORKSPACE_ID}" \
                           --authkey "${TAILSCALE_AUTHKEY}"
vscode:
  extensions:
    - ms-vscode.Theme-TomorrowKit

