image:
  file: /gitpod/Dockerfile

experimentalNetwork: true

tasks:
  - init: >
      ./gitpod/install.sh
  - name: dotfiles
    command: |
      if [ ! -d "~/.dotfiles" ]; then
        cd /tmp
        curl -sSL https://raw.githubusercontent.com/gbraad/dotfiles/master/install.sh -o /tmp/install.sh &&
        rm -f ~/.zshrc &&
        sh /tmp/install.sh
      fi
      mv ~/.bashrc-nochsh ~/.bashrc
  - name: github
    command: |
      gh auth login -h github.com -w
  - name: docker
    command: |
      sudo dnf install -y docker
  - name: sshd
    command: |
      sudo ssh-keygen -A && sudo /usr/sbin/sshd
      curl https://github.com/gbraad.keys | tee -a ~/.ssh/authorized_keys
  - name: tailscale
    command: |
      sudo --preserve-env=TAILSCALE_AUTHKEY /etc/init.d/tailscaled start
  - name: jupyter
    command: |
      pip install ipykernel

ports:
  - port: 22
    onOpen: ignore
  - port: 6080
    onOpen: open-preview

vscode:
  extensions:
    - ms-vscode.Theme-TomorrowKit
    - tailscale.vscode-tailscale
    - ms-toolsai.jupyter
    - ms-python.python