image: ghcr.io/gbraad/gitpod-devenv:0.3.0

experimentalNetwork: true

tasks:
  - init: >
      ./gitpod/install.sh
  - name: dotfiles
    command: |
      if [ ! -d "~/.dotfiles" ]; then
        cd /tmp
        curl -sSL https://raw.githubusercontent.com/gbraad/dotfiles/master/install.sh -o /tmp/install.sh &&
        sh /tmp/install.sh &&
        mv ~/.bashrc-nochsh ~/.bashrc
      fi
  - name: tailscaled
    command: |
      sudo tailscaled
  - name: tailscale
    command: |
      sudo -E tailscale up --hostname "gitpod-${GITPOD_WORKSPACE_ID}" \
                           --authkey "${TAILSCALE_AUTHKEY}"
  - name: github
    command: |
      gh auth login -h github.com -w
  - name: sshd
    command: |
      sudo ssh-keygen -A && sudo /usr/sbin/sshd
      curl https://github.com/gbraad.keys | tee -a ~/.ssh/authorized_keys

ports:
  - port: 22
    onOpen: ignore
  - port: 6080
    onOpen: open-preview

vscode:
  extensions:
    - ms-vscode.Theme-TomorrowKit

