FROM ghcr.io/gbraad-devenv/fedora/dotfiles:38

USER root

# for toolbox
RUN dnf install -y \
        zsh bc curl diffutils dnf-plugins-core findutils gnupg2 less lsof ncurses passwd pinentry procps-ng shadow-utils sudo time util-linux wget vte-profile \
    && dnf clean all \
    && rm -rf /var/cache/yum

USER gbraad