ARG BASE_VERSION="41"

FROM ghcr.io/gbraad-devenv/fedora/systemd:${BASE_VERSION}

LABEL org.opencontainers.image.source = "https://github.com/gbraad-devenv/fedora"

RUN cd /tmp \
    && curl -fL https://code.visualstudio.com/sha/download?build=stable\&os=cli-alpine-x64 -o code-cli.tar.gz \
    && tar zxvf code-cli.tar.gz \
    && mv code /usr/bin/code \
    && rm -f code-cli.tar.gz

# systemd
COPY assets/code-serveweb@.service /etc/systemd/system/

RUN systemctl enable code-serveweb@root.service

#ENTRYPOINT [ "/sbin/init" ]
