ARG BASE_IMAGE="quay.io/fedora/fedora"
ARG BASE_VERSION="41"

FROM ${BASE_IMAGE}:${BASE_VERSION} AS base

LABEL org.opencontainers.image.source = "https://github.com/gbraad-devenv/fedora"

USER root

# Add user with the expected ID (automated setup does not work atm)
RUN useradd -l -u 1000 -G wheel -md /home/gbraad -s /usr/bin/zsh -p gbraad gbraad \
    && sed -i.bkp -e 's/%wheel\s\+ALL=(ALL\(:ALL\)\?)\s\+ALL/%wheel ALL=NOPASSWD:ALL/g' /etc/sudoers

# essential packages
RUN dnf install -y \
        dnf-plugins-core git-core \
    && dnf clean all \
    && rm -rf /var/cache/yum

# install tailscale
RUN dnf config-manager addrepo --from-repofile=https://pkgs.tailscale.com/stable/fedora/tailscale.repo \
    && dnf install -y \
        tailscale \
    && dnf clean all \
    && rm -rf /var/cache/yum \
    && mkdir -p /var/run/tailscale /var/cache/tailscale /var/lib/tailscale

COPY assets/tailscaled /etc/init.d/tailscaled

# install cloudflared
#RUN dnf install -y \
#        https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-x86_64.rpm \
#    && dnf clean all \
#    && rm -rf /var/cache/yum

RUN dnf install -y \
        zsh mc vim tmux screen links lynx z stow wget procps-ng \
    && dnf clean all \
    && rm -rf /var/cache/yum

# dotfiles for root
RUN curl -sSL https://raw.githubusercontent.com/gbraad/dotfiles/master/install.sh | sh

# powerline
RUN dnf install -y \
        powerline vim-powerline tmux-powerline \
    && dnf clean all \
    && rm -rf /var/cache/yum

# optional for notebooks
RUN dnf install -y \
        python3-pip \
        python3-pygments \
    && dnf clean all \
    && rm -rf /var/cache/yum \
    && pip install ipykernel
    
# ranger
RUN dnf install -y \
        ranger \
        highlight \
    && dnf clean all \
    && rm -rf /var/cache/yum

# convenience tools
RUN dnf install -y \
        trash-cli \
        fzf \
        vgrep \
        fd-find \
        ripgrep \
    && dnf clean all \
    && rm -rf /var/cache/yum

# webdav (for tailscale drive shares and nextcloud)
RUN dnf install -y \
        davfs2 cadaver \
    && dnf clean all \
    && rm -rf /var/cache/yum

# github client
RUN dnf config-manager addrepo --from-repofile=https://cli.github.com/packages/rpm/gh-cli.repo \
    && dnf install -y \
       gh \
    && dnf clean all \
    && rm -rf /var/cache/yum

# change default shell for root
RUN chsh root -s /bin/zsh

# fix issue with sudo and SSH
RUN chmod 640 /etc/shadow

USER gbraad
