ARG BASE_VERSION="41"

FROM ghcr.io/gbraad-devenv/fedora/rebase:${BASE_VERSION}

LABEL org.opencontainers.image.source = "https://github.com/gbraad-devenv/fedora"

USER root

# vim
RUN dnf install -y \
        vim-syntastic-asciidoc \
        vim-syntastic-html \
        vim-syntastic-css \
        vim-syntastic-vim \
        vim-syntastic-yaml \
        vim-syntastic-json \
        vim-syntastic-go \
        vim-syntastic-zsh \
        vim-airline \
        vim-go \
        vim-ctrlp \
        vim-gitgutter \
        vim-fugitive \
        vim-nerdtree \
    && dnf clean all \
    && rm -rf /var/cache/yum

USER gbraad