ARG BASE_IMAGE="ghcr.io/gbraad-devenv/fedora/base"
ARG BASE_VERSION="41"

FROM ${BASE_IMAGE}:${BASE_VERSION}

ARG USER_PASSWD

LABEL org.opencontainers.image.source = "https://github.com/gbraad-devenv/fedora"

# Add user with the expected ID (automated setup does not work atm)
RUN useradd -l -u 1000 -G users,wheel -md /var/home/gbraad -s /bin/bash -p gbraad gbraad \
    && sed -i.bkp -e 's/%wheel\s\+ALL=(ALL\(:ALL\)\?)\s\+ALL/%wheel ALL=NOPASSWD:ALL/g' /etc/sudoers \
    && if [ -n "${USER_PASSWD}" ] ; then \
        echo "gbraad:${USER_PASSWD}" | sudo chpasswd && echo "Password set to: ${USER_PASSWD}"; \
    fi

USER gbraad

RUN rm -f ~/.zshrc \
    && git clone https://github.com/gbraad-dotfiles/upstream ~/.dotfiles \
    && ~/.dotfiles/install.sh \
    && sudo chsh gbraad -s /bin/zsh

RUN mkdir -p ~/.ssh/ \
    && curl https://github.com/gbraad.keys | tee -a ~/.ssh/authorized_keys

RUN pip install pygments-style-tomorrownightbright

ENTRYPOINT [ "/bin/zsh" ]
