ARG BASE_VERSION="41"

FROM ghcr.io/gbraad-devenv/fedora/systemd:${BASE_VERSION}

LABEL org.opencontainers.image.source = "https://github.com/gbraad-devenv/fedora"

# graphical
RUN dnf install -y \
        novnc \
        x11vnc \
        i3 \
        python3-i3ipc \
        feh \
    && dnf clean all \
    && rm -rf /var/cache/yum

# fonts
RUN dnf install -y \
        adobe-source-han-mono-fonts \
        adobe-source-code-pro-fonts \
        adobe-source-sans-pro-fonts \
        adobe-source-serif-pro-fonts \
        powerline-fonts \
    && dnf clean all \
    && rm -rf /var/cache/yum

RUN dnf install -y https://github.com/spotsnel/AltRPMS-KasmVNC/releases/download/1.3.3/kasmvncserver-1.3.3-1.fc41.x86_64.rpm \
    && dnf clean all \
    && rm -rf /var/cache/yum \
    && usermod -a -G kasmvnc-cert gbraad

COPY assets/kasmvncserver.service /etc/systemd/system

RUN sed -i 's/^FLAGS=".*"/FLAGS="--tun=userspace-networking"/' /etc/default/tailscaled

USER gbraad

RUN mkdir -p ~/.vnc \
    && echo $'#!/bin/sh\ni3 &' > ~/.vnc/xstartup \
    && chmod +x ~/.vnc/xstartup \
    && /bin/bash -c "echo -e 'password\npassword\n\n' | kasmvncpasswd -u gbraad -w" \
    && touch ~/.vnc/.de-was-selected    

# systemd is already set up in systemd image; make sure to use root
USER root

RUN systemctl enable kasmvncserver

#ENTRYPOINT ["/sbin/init"]
