FROM ghcr.io/gbraad-devenv/fedora/base:38

USER root

# vim
RUN dnf install -y \
        vim-syntastic-asciidoc \
        vim-syntastic-html \
        vim-syntastic-css \
        vim-syntastic-vim \
        vim-syntastic-yaml \
        vim-syntastic-json \
        vim-syntastic-go \
        vim-syntastic-zsh \
        vim-airline \
        vim-go \
        vim-ctrlp \
        vim-gitgutter \
        vim-fugitive \
        vim-nerdtree \
    && dnf clean all \
    && rm -rf /var/cache/yum

USER gbraad