name: tailscale-rdesktop-fedora-amd64-warpbuild

on:
  workflow_dispatch:

jobs:
  dotfiles-test:
    name: Tailscale rdesktop - Fedora AMD64
    uses: ./.github/workflows/reusable-tailscale-ssh-rdesktop.yml
    with:
      prefix_name: "desk"
      runs-on: "warp-ubuntu-latest-x64-2x"
      arch: "amd64"
      sudo-change-shell: true
    secrets: inherit
