name: tailscale-rdesktop-fedora-amd64

on:
  workflow_dispatch:

jobs:
  dotfiles-test:
    name: Tailscale rdesktop - Fedora AMD64
    uses: ./.github/workflows/reusable-tailscale-ssh-rdesktop.yml
    with:
      prefix_name: "desk"
      runs-on: "ubuntu-latest"
      arch: "amd64"
      sudo-change-shell: false
    secrets: inherit
