ARG BASE_IMAGE="ghcr.io/gbraad-dotfiles/fedora"
ARG BASE_VERSION="41"

FROM ${BASE_IMAGE}:${BASE_VERSION}

LABEL org.opencontainers.image.source = "https://github.com/gbraad-devenv/fedora"

ARG USER_PASSWD

USER root

# Add user with the expected ID (automated setup does not work atm)
RUN if [ -n "${USER_PASSWD}" ] ; then \
        echo "gbraad:${USER_PASSWD}" | sudo chpasswd && echo "Password set to: ${USER_PASSWD}"; \
    fi

RUN dnf install -y \
        mc links lynx z wget procps-ng \
    && dnf clean all \
    && rm -rf /var/cache/yum

# optional for notebooks
RUN dnf install -y \
        python3-pip \
        python3-pygments \
    && dnf clean all \
    && rm -rf /var/cache/yum \
    && pip install ipykernel
    
# ranger
RUN dnf install -y \
        ranger \
        highlight \
    && dnf clean all \
    && rm -rf /var/cache/yum

# convenience tools
RUN dnf install -y \
        trash-cli \
        vgrep \
        fd-find \
        ripgrep \
    && dnf clean all \
    && rm -rf /var/cache/yum

# webdav (for tailscale drive shares and nextcloud)
RUN dnf install -y \
        davfs2 cadaver \
    && dnf clean all \
    && rm -rf /var/cache/yum

# github client
RUN dnf config-manager addrepo --from-repofile=https://cli.github.com/packages/rpm/gh-cli.repo \
    && dnf install -y \
       gh \
    && dnf clean all \
    && rm -rf /var/cache/yum

USER gbraad

RUN pip install pygments-style-tomorrownightbright

USER root

RUN systemctl enable tailscaled

ENTRYPOINT ["/sbin/init"]
#CMD ["/sbin/init"]
