ARG BASE_IMAGE="ghcr.io/gbraad-devenv/fedora/rebase"
ARG BASE_VERSION="41"

FROM ${BASE_IMAGE}:${BASE_VERSION}

ARG USER_PASSWD

LABEL org.opencontainers.image.source = "https://github.com/gbraad-devenv/fedora"

# Add user with the expected ID (automated setup does not work atm)
RUN if [ -n "${USER_PASSWD}" ] ; then \
        echo "gbraad:${USER_PASSWD}" | sudo chpasswd && echo "Password set to: ${USER_PASSWD}"; \
    fi

USER gbraad

RUN pip install pygments-style-tomorrownightbright

ENTRYPOINT [ "/bin/zsh" ]
