name: build container - toolbox
run-name: building container - toolbox

on:
  workflow_dispatch:

jobs:
  build:
    name: build-container-toolbox
    permissions:
      contents: read
      packages: write
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run podman build - toolbox
        run: |
          podman build -t ghcr.io/gbraad-devenv/fedora/toolbox:41 \
            --build-arg=BASE_IMAGE="ghcr.io/gbraad-devenv/fedora/base" \
            --build-arg=BASE_VERSION=41 \
            -f containers/toolbox/Containerfile .
      - name: Push image to ghcr.io - toolbox
        run: |
          podman push --creds=${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} \
            ghcr.io/gbraad-devenv/fedora/toolbox:41
