name: build container - rdeskop + bootc
run-name: building container - rdesktop + bootc

on:
  workflow_dispatch:

jobs:
  build:
    name: build-container-rdesktop
    permissions:
      contents: read
      packages: write
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run podman build - rdesktop
        run: |
          podman build -t ghcr.io/gbraad-devenv/fedora/rdesktop:41 \
            --build-arg=BASE_IMAGE="ghcr.io/gbraad-devenv/fedora/systemd" \
            --build-arg=BASE_VERSION=41 \
            -f containers/rdesktop/Containerfile .
      - name: Push image to ghcr.io - rdesktop
        run: |
          podman push --creds=${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} \
            ghcr.io/gbraad-devenv/fedora/rdesktop:41
      - name: Run podman build - rdesktop-bootc
        run: |
          podman build -t ghcr.io/gbraad-devenv/fedora/rdesktop-bootc:41 \
            --build-arg=BASE_IMAGE="ghcr.io/gbraad-devenv/fedora/systemd-bootc" \
            --build-arg=BASE_VERSION=41 \
            -f containers/rdesktop/Containerfile .
      - name: Push image to ghcr.io - rdesktop-bootc
        run: |
          podman push --creds=${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} \
            ghcr.io/gbraad-devenv/fedora/rdesktop-bootc:41
