name: reusable-build-container

on:
  workflow_call:
    inputs:
      container_name:
        description: "Name of the container (e.g., base, code, rdesktop)"
        required: true
        type: string
      arch:
        description: "Architecture for the container (e.g., arm64, amd64)"
        required: true
        type: string
      base_image:
        description: "Base image identifier"
        required: true
        type: string
      base_version:
        description: "Base version identifier"
        required: true
        type: string

jobs:
  build:
    name: Build Container
    runs-on: ${{ inputs.arch == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Build container
        run: |
          podman build -t ghcr.io/${{ github.repository }}/${{ inputs.container_name }}:${{ inputs.arch }} \
            --build-arg=BASE_IMAGE="${{ inputs.base_image }}" \
            --build-arg=BASE_VERSION="${{ inputs.base_version }}" \
            --build-arg=ARCH="${{ inputs.arch }}" \
            -f containers/${{ inputs.container_name }}/Containerfile .

      - name: Save container as OCI
        run: |
          podman save ghcr.io/${{ github.repository }}/${{ inputs.container_name }}:${{ inputs.arch }} \
            --format=oci-dir -o ${{ inputs.container_name }}-oci-${{ inputs.arch }}

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.container_name }}-oci-${{ inputs.arch }}
          path: ${{ inputs.container_name }}-oci-${{ inputs.arch }}/
          retention-days: 7

      - name: Run podman export
        run: |
          podman create --name ${{ inputs.container_name }}-${{ inputs.arch }} \
            ghcr.io/${{ github.repository }}/${{ inputs.container_name }}:${{ inputs.arch }}
          podman export ${{ inputs.container_name }}-${{ inputs.arch }} -o ${{ inputs.container_name }}-${{ inputs.arch }}.tar
          gzip ${{ inputs.container_name }}-${{ inputs.arch }}.tar

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.container_name }}-rootfs-${{ inputs.arch }}
          path: ${{ inputs.container_name }}-${{ inputs.arch }}.tar.gz
          retention-days: 7