name: tailscale-code-fedora-amd64

on:
  workflow_dispatch:

jobs:
  dotfiles-test:
    name: Tailscale code - Fedora AMD64
    uses: ./.github/workflows/reusable-tailscale-ssh-code.yml
    with:
      prefix_name: "code"
      runs-on: "ubuntu-latest"
      arch: "amd64"
      sudo-change-shell: false
      mode: "serve-web"
    secrets: inherit
