name: tailscale-code-fedora-amd64-blacksmith

on:
  workflow_dispatch:

jobs:
  dotfiles-test:
    name: Tailscale rdesktop - Fedora AMD64
    uses: ./.github/workflows/reusable-tailscale-ssh-code.yml
    with:
      prefix_name: "code"
      runs-on: "blacksmith-2vcpu-ubuntu-2404"
      arch: "amd64"
      sudo-change-shell: true
    secrets: inherit
