name: tailscale-rdesktop
on:
  workflow_dispatch:

jobs:
  rdesktop-test:
    runs-on: ubuntu-24.04
    
    steps:
      - name: Remove unwanted stuff
        uses: gbraad-devenv/remove-unwanted@v1
      - name: Run system container with `podman`
        run: |
          podman run -d --name rdesktop --hostname code-${HOSTNAME} ghcr.io/gbraad-devenv/fedora/rdesktop:41
      - name: Tailscale setup (root)
        run: |
          until podman exec rdesktop tailscale up --auth-key ${TAILSCALE_AUTHKEY}
          do
              sleep 0.1
          done
          podman exec rdesktop tailscale set --ssh
          podman exec rdesktop chmod 640 /etc/shadow
        env:
          TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY}}
      - name: Hang around
        run: |
          until podman exec rdesktop systemctl is-active kasmvncserver
          do
               sleep 1
          done
          IP=`podman exec rdesktop tailscale ip -4`
          echo "Open in your web browser: https://${IP}:8444"
          sleep infinity
