name: tailscale-ssh-fedora-amd64

on:
  workflow_dispatch:

jobs:
  dotfiles-test:
    name: Tailscale SSH - Fedora AMD64
    uses: ./.github/workflows/reusable-tailscale-ssh-devenv.yml
    with:
      prefix_name: "fedora"
      runs-on: "ubuntu-latest"
      arch: "amd64"
      sudo-change-shell: false
    secrets: inherit
