name: tailscale-coder
on:
  workflow_dispatch:

jobs:
  coder-test:
    runs-on: ubuntu-24.04
    
    steps:
      - name: Run system container with `podman`
        run: |
          podman run -d --name coder ghcr.io/gbraad-devenv/fedora/coder:41
      - name: Tailscale setup (root)
        run: |
          until podman exec coder tailscale up --auth-key ${TAILSCALE_AUTHKEY} --hostname github-${HOSTNAME}
          do
              sleep 0.1
          done
          podman exec coder tailscale set --ssh
        env:
          TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY}}
      - name: Hang around
        run: |
          until podman exec coder systemctl is-active code-server@gbraad
          do
               sleep 1
          done
          IP=`podman exec coder tailscale ip -4`
          echo "Open in your web browser: https://${IP}:8080"
          podman exec coder cat ~gbraad/.config/code-server/config.yaml
          sleep infinity
